package tarea2;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class ejercicio {
	
	//verificar que el resultado devuelto por el test sea aproximadamente igual a 2.0 con un margen de error de 0.0001.
    @Test
    public void PruebaDivDosNumeros() {
        double result = problema9.divTwoNumbers(10, 5);
        assertEquals(2.0, result, 0.0001);
    }
    
    //verifica que el resultado devuelto por el test sea exactamente igual a 0.0 con un margen de error de 0.0001.
    @Test
    public void pruebaDividendoCero() {
        double result = problema9.divTwoNumbers(0, 5);
        assertEquals(0.0, result, 0.0001);
    }
    
    //La función assertThrows verifica si la ejecución arroja la excepción esperada.Si la excepción es arrojada, el test pasa satisfactoriamente.
    @Test
    public void PruebaDivPorCero() {
    	assertThrows(IllegalArgumentException.class, () -> problema9.divTwoNumbers(10, 0));
        }
    
    //verificar si el método divTwoNumbers maneja correctamente la situación en la que se intenta dividir 0 por 0 y debería arrojar una excepción.
    @Test
    public void pruebaAmbosCero() {
        assertThrows(IllegalArgumentException.class, () -> problema9.divTwoNumbers(0, 0));
    }
}
